resources:
- deployment.yml
- service.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: webfrontend-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - ConnectionStrings__cache=cache:6379
    - services__apiservice__http__0=http://apiservice:8080
    - ASPNETCORE_URLS=http://+:8080;

